device: "cuda"
epochs: 100
val_every_n_epochs: 1
compute_metrics_n_val_epoch: 2
load_checkpoint: false
resume_training: false

criterion:
  name: CrossEntropyLoss

optimizer:
  name: Adam
  lr: 1e-4
  weight_decay: 1e-5

scheduler:
  name: ReduceLROnPlateau
  mode: "min"
  factor: 0.1
  patience: 4

early_stopping:
  patience: 10
  delta: 0.001

checkpoint:
  save_dir: "models/checkpoints"
  filename: "${logging.run_name}.pt"
  patience: 2
  vebose: true

export:
  export_after_training: true
  save_dir: "models/exported"
  filename: "${logging.run_name}.onnx"
  validate_export: true